### ISSUE TITLE
Create the RSS Feed 

### ISSUE THREAD

**Issue by Monica-Vu** [Technolgap/technolgap-website#3]
**Context**
We need a way to display our social media activity. An RSS Feed is the way to go! 

**Problem**
We don't have one...yet.

**Acceptance Criteria:**
* The appearance of this component's desktop version must be exact or (very) similar to the approved [Figma Mock-up](https://www.figma.com/file/ciTL29R7gAaKkipH6v8QLL/Technolgap-official-Mockups?node-id=483%3A0)

<img width="637" alt="Screen Shot 2020-08-23 at 8 42 35 AM" src="https://user-images.githubusercontent.com/33503336/90978532-a5b26b80-e51c-11ea-8ab0-0dacc896a53e.png">

Note: you're not responsible for the `Title` component. It is covered in #7 but you will have to call it.

* Check if the following social media pages allow you to embed it to the website: 

- [ ] Linkedin
- [ ] Twitter
- [ ] Instagram
- [ ]  Medium
- [ ]  Facebook

* For each one that is allowed, incorporate it into the website 

* Make sure it still looks good on mobile (suggestion: use Flexbox or CSS Grids) 

* It should have the title component (primary header with underline)

**Comment by mSitkovets** [comment]
Update: I'm going to be doing one Twitter card and one Instagram card (per Alexa's request) and in the future we will add a Medium card as well.
