### ISSUE TITLE
Create the Footer

### ISSUE THREAD

**Issue by Monica-Vu** [Technolgap/technolgap-website#6]
**Context**
We need a way for users to see our social media links. We can attach it to the footer (since we need one anyway) 

**Problem**
We don't this feature yet...yet.

**Acceptance Criteria:**
* The appearance of this component's desktop version must be exact or (very) similar to the approved  [Figma Mockup](https://www.figma.com/file/ciTL29R7gAaKkipH6v8QLL/Technolgap-official-Mockups?node-id=511%3A661)
<img width="379" alt="Screen Shot 2020-08-23 at 8 58 37 AM" src="https://user-images.githubusercontent.com/33503336/90978879-00e55d80-e51f-11ea-8276-140b613e5883.png">

* The mobile version should not have the SVG's on the left or right side 
<img width="465" alt="Screen Shot 2020-08-23 at 8 58 47 AM" src="https://user-images.githubusercontent.com/33503336/90978961-7fda9600-e51f-11ea-806e-640f0cd48d09.png">

* When the user hovers or clicks on the social media icon, it should reflect the appearance when it's hovered and when clicked, it should open a new tab to the respective social media account account. See below for reference image:
![Footer (Hovered)](https://user-images.githubusercontent.com/33503336/90978953-72bda700-e51f-11ea-9969-a189d30c24bf.jpg)

**Reference**
* See footer at http://www.harvardwics.com/

**Comment by venesmargie** [comment]
Hi! I can't see this in the pull request options, and I was wondering how I can do that 😅😅

I do have some issues, the footer background doesnt completely "sink" to the bottom so there's a small gap. But, social media buttons are working perfectly! I wanted to let you guys see what I have done so far! Thank you for your patience!
